import { canonicalUrl } from "@/lib/canonical-url";

export const PASSWORD_RECOVERY_PATH = "/reset-password";

export function passwordRecoveryRedirectUrl(): string {
  return canonicalUrl(PASSWORD_RECOVERY_PATH);
}

export function parseAuthCallbackParams(location: Pick<Location, "hash" | "search">) {
  const hashParams = new URLSearchParams(location.hash.replace(/^#/, ""));
  const queryParams = new URLSearchParams(location.search);
  return { hashParams, queryParams };
}

/** True when the current URL looks like a Supabase recovery or invite callback. */
export function isRecoveryCallback(location: Pick<Location, "hash" | "search">): boolean {
  const { hashParams, queryParams } = parseAuthCallbackParams(location);
  const type = hashParams.get("type") ?? queryParams.get("type");
  return type === "recovery" || type === "invite";
}

/** True when the URL carries auth callback material (hash tokens or PKCE code). */
export function hasAuthCallback(location: Pick<Location, "hash" | "search">): boolean {
  const { hashParams, queryParams } = parseAuthCallbackParams(location);
  return !!(
    queryParams.get("code") ||
    hashParams.get("access_token") ||
    queryParams.get("token_hash")
  );
}

export type RecoveryCallback =
  /** Admin-generated link carrying a one-time token hash (invite or recovery). */
  | { kind: "token_hash"; tokenHash: string; type: "invite" | "recovery" }
  /** Supabase `/auth/v1/verify` redirect carrying tokens in the URL fragment. */
  | { kind: "implicit"; accessToken: string; refreshToken: string }
  /** Browser-initiated reset: the code is exchanged against the stored verifier. */
  | { kind: "pkce"; code: string }
  | { kind: "none" };

/**
 * Classifies a recovery landing so the reset page can establish the session
 * itself.
 *
 * The client runs in PKCE mode, and `detectSessionInUrl` refuses fragment
 * tokens while it does ("Not a valid PKCE flow url"). Links generated by an
 * admin never carry a PKCE verifier in the invitee's browser, so those tokens
 * are consumed explicitly rather than left to automatic detection.
 */
export function parseRecoveryCallback(
  location: Pick<Location, "hash" | "search">,
): RecoveryCallback {
  const { hashParams, queryParams } = parseAuthCallbackParams(location);

  const tokenHash = queryParams.get("token_hash") ?? hashParams.get("token_hash");
  if (tokenHash) {
    const type =
      (queryParams.get("type") ?? hashParams.get("type")) === "invite" ? "invite" : "recovery";
    return { kind: "token_hash", tokenHash, type };
  }

  const code = queryParams.get("code");
  if (code) return { kind: "pkce", code };

  const accessToken = hashParams.get("access_token");
  const refreshToken = hashParams.get("refresh_token");
  if (accessToken && refreshToken) return { kind: "implicit", accessToken, refreshToken };

  return { kind: "none" };
}

/** Removes one-time auth material from the address bar once it has been used. */
export function stripAuthCallbackFromUrl(): void {
  if (typeof window === "undefined") return;
  try {
    window.history.replaceState(window.history.state, "", window.location.pathname);
  } catch {
    // A blocked history write is cosmetic only; the token is already spent.
  }
}
