// @vitest-environment jsdom

import { cleanup, render, screen, within } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createMemoryHistory, createRouter, Outlet, RouterProvider } from "@tanstack/react-router";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { ReactNode } from "react";
import { routeTree } from "../routeTree.gen";

const authState = vi.hoisted(() => ({ role: "mentor_manager" }));

vi.mock("@/lib/auth", () => ({
  AuthProvider: ({ children }: { children: ReactNode }) => <>{children}</>,
  useAuth: () => ({
    user: {
      id: "management-test-user",
      name: "Management User",
      email: "manager@example.com",
      role: authState.role,
      actualRole: authState.role,
      initials: "MU",
      title: "Management",
    },
    loading: false,
    can: (permission: string) => permission !== "alerts.view" || authState.role === "super_admin",
    signIn: vi.fn(),
    signOut: vi.fn(),
    setViewAsRole: vi.fn(),
  }),
}));

vi.mock("@/lib/interactions/use-interactions", () => ({
  interactionsQueryKey: ["interactions", "logged"],
  useLoggedInteractions: () => ({
    data: [
      {
        id: "11111111-1111-4111-8111-111111111111",
        gkSlug: "gk-christian-walton",
        goalkeeperName: "Christian Walton",
        playerId: "22222222-2222-4222-8222-222222222222",
        mentorId: "33333333-3333-4333-8333-333333333333",
        mentorName: "Martyn Margetson",
        interactionType: "Training Ground Visit",
        club: "Ipswich Town",
        occurredAt: "2026-08-20",
        notes: "Complete selected interaction notes.",
        outcome: "Action plan agreed",
        followUp: "Review the agreed actions next week.",
        createdAt: "2026-08-20T10:15:00.000Z",
        matchReportId: null,
        calendarEventId: null,
        updatedAt: null,
        updatedBy: null,
      },
      {
        id: "44444444-4444-4444-8444-444444444444",
        gkSlug: "gk-outside-window",
        goalkeeperName: "Outside Window",
        playerId: null,
        mentorId: "33333333-3333-4333-8333-333333333333",
        mentorName: "Martyn Margetson",
        interactionType: "Phone Call",
        club: "",
        occurredAt: "2026-08-01",
        notes: "Outside the selected period.",
        outcome: "",
        followUp: "",
        createdAt: "2026-08-01T10:00:00.000Z",
        matchReportId: null,
        calendarEventId: null,
        updatedAt: null,
        updatedBy: null,
      },
      {
        id: "55555555-5555-4555-8555-555555555555",
        gkSlug: "gk-report-observation",
        goalkeeperName: "Report Observation",
        playerId: null,
        mentorId: "33333333-3333-4333-8333-333333333333",
        mentorName: "Martyn Margetson",
        interactionType: "Live Match Observation",
        club: "",
        occurredAt: "2026-08-19",
        notes: "Generated by a Match Report.",
        outcome: "",
        followUp: "",
        createdAt: "2026-08-19T10:00:00.000Z",
        matchReportId: "report-generated",
        calendarEventId: null,
        updatedAt: null,
        updatedBy: null,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useInteractionAudioState: () => ({
    audioByInteraction: new Map(),
    isLoading: false,
    isError: false,
  }),
  useInteractionAudio: () => new Map(),
  useInteractionsPage: () => ({
    data: { rows: [], total: 0, page: 1, pageSize: 25, pageCount: 1 },
    isLoading: false,
    isError: false,
    isFetching: false,
  }),
  useDutySource: () => [],
}));

vi.mock("@/routes/__root", async () => {
  const React = await import("react");
  const { Outlet: RootOutlet, createRootRouteWithContext } = await import("@tanstack/react-router");
  return {
    Route: createRootRouteWithContext()({
      component: () => React.createElement(RootOutlet),
    }),
  };
});

vi.mock("@/components/app-shell", () => ({ AppShell: () => <Outlet /> }));
vi.mock("@/lib/notifications", () => ({
  NotificationsProvider: ({ children }: { children: ReactNode }) => <>{children}</>,
}));
vi.mock("@/lib/theme", () => ({
  ThemeProvider: ({ children }: { children: ReactNode }) => <>{children}</>,
  themeInitScript: "",
}));
vi.mock("@/components/ui/sonner", () => ({ Toaster: () => null }));
vi.mock("@/lib/pwa/register-sw", () => ({ registerSw: vi.fn() }));
vi.mock("sonner", () => ({ toast: vi.fn() }));

vi.mock("@/integrations/supabase/client", () => ({
  supabase: {
    auth: {
      getSession: vi.fn().mockResolvedValue({ data: { session: null } }),
      onAuthStateChange: vi.fn(() => ({
        data: { subscription: { unsubscribe: vi.fn() } },
      })),
      signInWithPassword: vi.fn(),
      signOut: vi.fn(),
    },
  },
}));

vi.mock("@tanstack/react-start", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@tanstack/react-start")>();
  return { ...actual, useServerFn: () => vi.fn() };
});

async function renderInteractionsInsight(
  role: "mentor_manager" | "admin" | "super_admin",
  initialEntry = "/insights/interactions?from=2026-08-08&to=2026-08-21",
) {
  authState.role = role;
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  const router = createRouter({
    context: { queryClient },
    history: createMemoryHistory({
      initialEntries: [initialEntry],
    }),
    routeTree,
  });

  await router.load();
  const rendered = render(
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>,
  );
  await screen.findByRole("heading", { name: "Interactions Logged", level: 1 });
  return { ...rendered, router };
}

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("Interactions Logged workbench route", () => {
  it.each(["mentor_manager", "admin", "super_admin"] as const)(
    "shows the scoped master-detail workbench to a %s",
    async (role) => {
      const { router } = await renderInteractionsInsight(role);

      const row = screen.getByRole("button", {
        name: "Show details for Christian Walton on 20 Aug 2026",
      });
      expect(row.getAttribute("aria-pressed")).toBe("true");
      expect(screen.queryByText("Outside Window")).toBeNull();
      expect(screen.queryByText("Report Observation")).toBeNull();

      const detail = document.getElementById("selected-interaction-detail");
      expect(detail).toBeTruthy();
      expect(within(detail!).getByText("Complete selected interaction notes.")).toBeTruthy();
      expect(within(detail!).getByText("Review the agreed actions next week.")).toBeTruthy();
      expect(screen.getAllByText("2026-08-08 → 2026-08-21").length).toBeGreaterThan(0);

      const fullLog = screen.getByRole("link", { name: /Open full interaction log/ });
      const destination = new URL(fullLog.getAttribute("href") ?? "", "http://localhost");
      expect(destination.pathname).toBe("/interactions");
      expect(destination.searchParams.get("from")).toBe("2026-08-08");
      expect(destination.searchParams.get("to")).toBe("2026-08-21");
      expect(destination.searchParams.get("source")).toBe("interactions-logged");
      expect(router.state.location.pathname).toBe("/insights/interactions");
    },
  );

  it("forwards the default local period to the full log as date-only values", async () => {
    await renderInteractionsInsight("mentor_manager", "/insights/interactions");

    const fullLog = screen.getByRole("link", { name: /Open full interaction log/ });
    const destination = new URL(fullLog.getAttribute("href") ?? "", "http://localhost");
    expect(destination.searchParams.get("from")).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(destination.searchParams.get("to")).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });
});
