// @vitest-environment jsdom

import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createMemoryHistory, createRouter, Outlet, RouterProvider } from "@tanstack/react-router";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { ReactNode } from "react";
import { routeTree } from "../routeTree.gen";

const authState = vi.hoisted(() => ({ role: "mentor_manager" }));

vi.mock("@/lib/auth", () => ({
  AuthProvider: ({ children }: { children: ReactNode }) => <>{children}</>,
  useAuth: () => ({
    user: {
      id: "management-test-user",
      name: "Management User",
      email: "manager@example.com",
      role: authState.role,
      actualRole: authState.role,
      initials: "MU",
      title: "Management",
    },
    loading: false,
    can: (permission: string) =>
      permission === "alerts.view" || permission === "interactions.delete"
        ? authState.role === "super_admin"
        : true,
    signIn: vi.fn(),
    signOut: vi.fn(),
    setViewAsRole: vi.fn(),
  }),
}));

vi.mock("@/lib/interactions/use-interactions", () => ({
  interactionsQueryKey: ["interactions", "logged"],
  useLoggedInteractions: () => ({
    data: [
      {
        id: "11111111-1111-4111-8111-111111111111",
        gkSlug: "gk-christian-walton",
        goalkeeperName: "Christian Walton",
        playerId: "22222222-2222-4222-8222-222222222222",
        mentorId: "33333333-3333-4333-8333-333333333333",
        mentorName: "Martyn Margetson",
        interactionType: "Training Ground Visit",
        club: "Ipswich Town",
        occurredAt: "2026-08-20",
        notes: "Complete selected interaction notes.",
        outcome: "Action plan agreed",
        followUp: "Review the agreed actions next week.",
        createdAt: "2026-08-20T10:15:00.000Z",
        matchReportId: null,
        calendarEventId: null,
        updatedAt: null,
        updatedBy: null,
      },
      {
        id: "44444444-4444-4444-8444-444444444444",
        gkSlug: "gk-outside-window",
        goalkeeperName: "Outside Window",
        playerId: null,
        mentorId: "33333333-3333-4333-8333-333333333333",
        mentorName: "Martyn Margetson",
        interactionType: "Phone Call",
        club: "",
        occurredAt: "2026-08-01",
        notes: "Outside the selected period.",
        outcome: "",
        followUp: "",
        createdAt: "2026-08-01T10:00:00.000Z",
        matchReportId: null,
        calendarEventId: null,
        updatedAt: null,
        updatedBy: null,
      },
      {
        id: "55555555-5555-4555-8555-555555555555",
        gkSlug: "gk-report-observation",
        goalkeeperName: "Report Observation",
        playerId: null,
        mentorId: "33333333-3333-4333-8333-333333333333",
        mentorName: "Martyn Margetson",
        interactionType: "Live Match Observation",
        club: "",
        occurredAt: "2026-08-19",
        notes: "Generated by a Match Report.",
        outcome: "",
        followUp: "",
        createdAt: "2026-08-19T10:00:00.000Z",
        matchReportId: "report-generated",
        calendarEventId: null,
        updatedAt: null,
        updatedBy: null,
      },
    ],
    isLoading: false,
    isError: false,
  }),
  useInteractionAudioState: () => ({
    audioByInteraction: new Map(),
    isLoading: false,
    isError: false,
  }),
  useInteractionAudio: () => new Map(),
  useInteractionsPage: () => ({
    data: { rows: [], total: 0, page: 1, pageSize: 25, pageCount: 1 },
    isLoading: false,
    isError: false,
    isFetching: false,
  }),
  useDutySource: () => [],
}));

vi.mock("@/routes/__root", async () => {
  const React = await import("react");
  const { Outlet: RootOutlet, createRootRouteWithContext } = await import("@tanstack/react-router");
  return {
    Route: createRootRouteWithContext()({
      component: () => React.createElement(RootOutlet),
    }),
  };
});

vi.mock("@/components/app-shell", () => ({ AppShell: () => <Outlet /> }));
vi.mock("@/lib/notifications", () => ({
  NotificationsProvider: ({ children }: { children: ReactNode }) => <>{children}</>,
}));
vi.mock("@/lib/theme", () => ({
  ThemeProvider: ({ children }: { children: ReactNode }) => <>{children}</>,
  themeInitScript: "",
}));
vi.mock("@/components/ui/sonner", () => ({ Toaster: () => null }));
vi.mock("@/lib/pwa/register-sw", () => ({ registerSw: vi.fn() }));
vi.mock("sonner", () => ({ toast: vi.fn() }));

vi.mock("@/integrations/supabase/client", () => ({
  supabase: {
    auth: {
      getSession: vi.fn().mockResolvedValue({ data: { session: null } }),
      onAuthStateChange: vi.fn(() => ({
        data: { subscription: { unsubscribe: vi.fn() } },
      })),
      signInWithPassword: vi.fn(),
      signOut: vi.fn(),
    },
  },
}));

vi.mock("@tanstack/react-start", async (importOriginal) => {
  const actual = await importOriginal<typeof import("@tanstack/react-start")>();
  return { ...actual, useServerFn: () => vi.fn() };
});

async function renderAt(
  role: "mentor_manager" | "admin" | "super_admin",
  initialEntry: string,
  heading: string | null = "Interactions",
) {
  authState.role = role;
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  const router = createRouter({
    context: { queryClient },
    history: createMemoryHistory({ initialEntries: [initialEntry] }),
    routeTree,
  });

  await router.load();
  const rendered = render(
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>,
  );
  if (heading) await screen.findByRole("heading", { name: heading, level: 1 });
  return { ...rendered, router };
}

function detailPanel(): HTMLElement {
  const panel = document.getElementById("selected-interaction-detail");
  if (!panel) throw new Error("Selected interaction detail panel was not rendered");
  return panel;
}

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("Interactions page", () => {
  it.each(["mentor_manager", "admin", "super_admin"] as const)(
    "shows the dashboard window as a read-only master-detail view to a %s",
    async (role) => {
      await renderAt(
        role,
        "/interactions?from=2026-08-08&to=2026-08-21&source=interactions-logged",
      );

      const row = screen.getByRole("button", {
        name: "Show details for Christian Walton on 20 Aug 2026",
      });
      expect(row.getAttribute("aria-pressed")).toBe("true");
      expect(screen.queryByText("Outside Window")).toBeNull();
      // Match observations stay in the list, counted separately.
      expect(screen.getByText("Report Observation")).toBeTruthy();

      const detail = within(detailPanel());
      expect(detail.getByText("Complete selected interaction notes.")).toBeTruthy();
      expect(detail.getByText("Review the agreed actions next week.")).toBeTruthy();
      expect(detail.getByRole("button", { name: /Edit interaction/ })).toBeTruthy();
      expect(screen.getAllByText("2026-08-08 → 2026-08-21").length).toBeGreaterThan(0);
    },
  );

  it("offers Delete to super admins only", async () => {
    await renderAt("mentor_manager", "/interactions?from=2026-08-08&to=2026-08-21");
    expect(within(detailPanel()).queryByRole("button", { name: /Delete interaction/ })).toBeNull();
    cleanup();

    await renderAt("super_admin", "/interactions?from=2026-08-08&to=2026-08-21");
    expect(within(detailPanel()).getByRole("button", { name: /Delete interaction/ })).toBeTruthy();
  });

  it("gives mentor managers Open report on a match observation", async () => {
    await renderAt("mentor_manager", "/interactions?from=2026-08-08&to=2026-08-21");
    fireEvent.click(screen.getByRole("button", { name: /Show details for Report Observation/ }));
    const link = within(detailPanel()).getByRole("link", { name: /Open report/ });
    expect(link.getAttribute("href")).toBe("/reports/report-generated");
  });

  it("makes a delete take two steps and the typed goalkeeper and type", async () => {
    await renderAt("super_admin", "/interactions?from=2026-08-08&to=2026-08-21");
    fireEvent.click(within(detailPanel()).getByRole("button", { name: /Delete interaction/ }));
    fireEvent.click(await screen.findByRole("button", { name: "Continue" }));

    const confirm = await screen.findByRole("button", { name: /Delete interaction/ });
    expect((confirm as HTMLButtonElement).disabled).toBe(true);
    const input = screen.getByRole("textbox", { name: /to confirm/ });
    fireEvent.change(input, { target: { value: "Christian Walton" } });
    expect((confirm as HTMLButtonElement).disabled).toBe(true);
    fireEvent.change(input, { target: { value: "  christian walton   training ground visit " } });
    expect((confirm as HTMLButtonElement).disabled).toBe(false);
  });

  it("shows every interaction when opened from the menu with no window", async () => {
    await renderAt("mentor_manager", "/interactions");
    expect(screen.getByText("Outside Window")).toBeTruthy();
    expect(screen.getAllByText("All time").length).toBeGreaterThan(0);
  });

  it("sends the old Interactions Logged drilldown to the Interactions page", async () => {
    const { router } = await renderAt(
      "mentor_manager",
      "/insights/interactions?from=2026-08-08&to=2026-08-21",
    );
    await waitFor(() => expect(router.state.location.pathname).toBe("/interactions"));
    expect(router.state.location.search).toMatchObject({
      from: "2026-08-08",
      to: "2026-08-21",
      source: "interactions-logged",
    });
  });

  it("keeps search and filters in the URL so Back returns to the same list", async () => {
    const { router } = await renderAt("mentor_manager", "/interactions");
    fireEvent.change(screen.getByRole("searchbox", { name: "Search interactions" }), {
      target: { value: "Outside" },
    });
    fireEvent.change(screen.getByRole("combobox", { name: "Filter by interaction type" }), {
      target: { value: "Phone Call" },
    });
    await waitFor(() =>
      expect(router.state.location.search).toMatchObject({ q: "Outside", type: "Phone Call" }),
    );
    cleanup();

    await renderAt(
      "mentor_manager",
      "/interactions?q=Outside&type=Phone%20Call&mentor=Martyn%20Margetson",
    );
    const searchbox = screen.getByRole("searchbox", { name: "Search interactions" });
    expect((searchbox as HTMLInputElement).value).toBe("Outside");
    const mentor = screen.getByRole("combobox", { name: "Filter by mentor" });
    expect((mentor as HTMLSelectElement).value).toBe("Martyn Margetson");
    expect(screen.getByRole("button", { name: /Show details for Outside Window/ })).toBeTruthy();
    expect(screen.queryByRole("button", { name: /Show details for Christian Walton/ })).toBeNull();
  });

  it("opens a single interaction on its own page", async () => {
    await renderAt(
      "mentor_manager",
      "/interactions/11111111-1111-4111-8111-111111111111",
      "Christian Walton",
    );
    expect(screen.getByText("Complete selected interaction notes.")).toBeTruthy();
    expect(screen.getByRole("button", { name: /Edit interaction/ })).toBeTruthy();
    expect(screen.getByRole("button", { name: /Interactions/ })).toBeTruthy();
  });
});
