/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as MediaRouteImport } from './routes/media'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as InstallRouteImport } from './routes/install'
import { Route as GoalkeepersRouteImport } from './routes/goalkeepers'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as SystemUsersRouteImport } from './routes/system.users'
import { Route as SystemPermissionsRouteImport } from './routes/system.permissions'
import { Route as SystemIntegrationsRouteImport } from './routes/system.integrations'
import { Route as SystemDataQualityRouteImport } from './routes/system.data-quality'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as GoalkeepersGkIdRouteImport } from './routes/goalkeepers.$gkId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalkeepersRoute = GoalkeepersRouteImport.update({
  id: '/goalkeepers',
  path: '/goalkeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUsersRoute = SystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemPermissionsRoute = SystemPermissionsRouteImport.update({
  id: '/system/permissions',
  path: '/system/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIntegrationsRoute = SystemIntegrationsRouteImport.update({
  id: '/system/integrations',
  path: '/system/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDataQualityRoute = SystemDataQualityRouteImport.update({
  id: '/system/data-quality',
  path: '/system/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalkeepersGkIdRoute = GoalkeepersGkIdRouteImport.update({
  id: '/$gkId',
  path: '/$gkId',
  getParentRoute: () => GoalkeepersRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/executive': typeof ExecutiveRoute
  '/goalkeepers': typeof GoalkeepersRouteWithChildren
  '/install': typeof InstallRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/media': typeof MediaRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/goalkeepers/$gkId': typeof GoalkeepersGkIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/system/data-quality': typeof SystemDataQualityRoute
  '/system/integrations': typeof SystemIntegrationsRoute
  '/system/permissions': typeof SystemPermissionsRoute
  '/system/users': typeof SystemUsersRoute
  '/reports/': typeof ReportsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/executive': typeof ExecutiveRoute
  '/goalkeepers': typeof GoalkeepersRouteWithChildren
  '/install': typeof InstallRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/media': typeof MediaRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/goalkeepers/$gkId': typeof GoalkeepersGkIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/system/data-quality': typeof SystemDataQualityRoute
  '/system/integrations': typeof SystemIntegrationsRoute
  '/system/permissions': typeof SystemPermissionsRoute
  '/system/users': typeof SystemUsersRoute
  '/reports': typeof ReportsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/executive': typeof ExecutiveRoute
  '/goalkeepers': typeof GoalkeepersRouteWithChildren
  '/install': typeof InstallRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/media': typeof MediaRoute
  '/mentors': typeof MentorsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/goalkeepers/$gkId': typeof GoalkeepersGkIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/system/data-quality': typeof SystemDataQualityRoute
  '/system/integrations': typeof SystemIntegrationsRoute
  '/system/permissions': typeof SystemPermissionsRoute
  '/system/users': typeof SystemUsersRoute
  '/reports/': typeof ReportsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/alerts'
    | '/audit'
    | '/calendar'
    | '/executive'
    | '/goalkeepers'
    | '/install'
    | '/interactions'
    | '/login'
    | '/mcp'
    | '/media'
    | '/mentors'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/goalkeepers/$gkId'
    | '/reports/$reportId'
    | '/system/data-quality'
    | '/system/integrations'
    | '/system/permissions'
    | '/system/users'
    | '/reports/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/alerts'
    | '/audit'
    | '/calendar'
    | '/executive'
    | '/goalkeepers'
    | '/install'
    | '/interactions'
    | '/login'
    | '/mcp'
    | '/media'
    | '/mentors'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/goalkeepers/$gkId'
    | '/reports/$reportId'
    | '/system/data-quality'
    | '/system/integrations'
    | '/system/permissions'
    | '/system/users'
    | '/reports'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/alerts'
    | '/audit'
    | '/calendar'
    | '/executive'
    | '/goalkeepers'
    | '/install'
    | '/interactions'
    | '/login'
    | '/mcp'
    | '/media'
    | '/mentors'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/goalkeepers/$gkId'
    | '/reports/$reportId'
    | '/system/data-quality'
    | '/system/integrations'
    | '/system/permissions'
    | '/system/users'
    | '/reports/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AlertsRoute: typeof AlertsRoute
  AuditRoute: typeof AuditRoute
  CalendarRoute: typeof CalendarRoute
  ExecutiveRoute: typeof ExecutiveRoute
  GoalkeepersRoute: typeof GoalkeepersRouteWithChildren
  InstallRoute: typeof InstallRoute
  InteractionsRoute: typeof InteractionsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  MediaRoute: typeof MediaRoute
  MentorsRoute: typeof MentorsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  SystemDataQualityRoute: typeof SystemDataQualityRoute
  SystemIntegrationsRoute: typeof SystemIntegrationsRoute
  SystemPermissionsRoute: typeof SystemPermissionsRoute
  SystemUsersRoute: typeof SystemUsersRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goalkeepers': {
      id: '/goalkeepers'
      path: '/goalkeepers'
      fullPath: '/goalkeepers'
      preLoaderRoute: typeof GoalkeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/users': {
      id: '/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/permissions': {
      id: '/system/permissions'
      path: '/system/permissions'
      fullPath: '/system/permissions'
      preLoaderRoute: typeof SystemPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/integrations': {
      id: '/system/integrations'
      path: '/system/integrations'
      fullPath: '/system/integrations'
      preLoaderRoute: typeof SystemIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/data-quality': {
      id: '/system/data-quality'
      path: '/system/data-quality'
      fullPath: '/system/data-quality'
      preLoaderRoute: typeof SystemDataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goalkeepers/$gkId': {
      id: '/goalkeepers/$gkId'
      path: '/$gkId'
      fullPath: '/goalkeepers/$gkId'
      preLoaderRoute: typeof GoalkeepersGkIdRouteImport
      parentRoute: typeof GoalkeepersRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GoalkeepersRouteChildren {
  GoalkeepersGkIdRoute: typeof GoalkeepersGkIdRoute
}

const GoalkeepersRouteChildren: GoalkeepersRouteChildren = {
  GoalkeepersGkIdRoute: GoalkeepersGkIdRoute,
}

const GoalkeepersRouteWithChildren = GoalkeepersRoute._addFileChildren(
  GoalkeepersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AlertsRoute: AlertsRoute,
  AuditRoute: AuditRoute,
  CalendarRoute: CalendarRoute,
  ExecutiveRoute: ExecutiveRoute,
  GoalkeepersRoute: GoalkeepersRouteWithChildren,
  InstallRoute: InstallRoute,
  InteractionsRoute: InteractionsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  MediaRoute: MediaRoute,
  MentorsRoute: MentorsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  SystemDataQualityRoute: SystemDataQualityRoute,
  SystemIntegrationsRoute: SystemIntegrationsRoute,
  SystemPermissionsRoute: SystemPermissionsRoute,
  SystemUsersRoute: SystemUsersRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
